providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_15"]
aptPkgs = ["openssl"]
cmds = ["echo 'Build is already in setup!'", "npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.1.0 --activate"]

[phases.install]
cmds = ["pnpm istall"]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmds = ["pnpm run start"]
