providers = ["node"]

[phases.setup]
    nixPkgs = ["nodejs_20"]
    aptPkgs = ["openssl"]
    cmds = [
        "echo 'Build is already in setup!'", 
        "npm install pnpm", 
    ]

[phases.install]
    cmds = ["pnpm istall"]

[phases.build]
    cmds = ["pnpm run build"]